In [42]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split



In [6]:
X_false = np.arange(10)
X_false

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.seed(1)
train_test_split(X_false, test_size=0.5)

[array([3, 1, 7, 8, 5]), array([2, 9, 6, 4, 0])]

In [43]:
np.random.seed(1)
X_treino, X_valid, y_treino, y_valid = train_test_split(X, y, test_size=0.5)

In [44]:
X_treino.head()

Sex_binario    Age
394            1  24.00
851            0  74.00
373            0  22.00
523            1  44.00
78             0   0.83

In [45]:
X_treino.shape, X_valid.shape, y_treino.shape, y_valid.shape

((445, 2), (446, 2), (445,), (446,))

In [46]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [47]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [48]:
model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
model.fit(X_treino, y_treino)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [49]:
p = model.predict(X_valid)

In [50]:
np.mean(y_valid == p)

0.7466367713004485

In [51]:
p = (X_valid['Sex_binario'] == 1).astype(np.int64)
np.mean(y_valid == p)

0.7623318385650224

In [52]:
## Validação Cruzada Cross Validation

In [53]:
X_false

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
?KFold

In [55]:
from sklearn.model_selection import KFold

In [21]:
kf = KFold(3, shuffle=True, random_state=0)
for linhas_treino, linhas_valid in kf.split(X_false):
    print('Treino', linhas_treino)
    print('Valid', linhas_valid)
    print()

Treino [0 1 3 5 6 7]
Valid [2 4 8 9]

Treino [0 2 3 4 5 8 9]
Valid [1 6 7]

Treino [1 2 4 6 7 8 9]
Valid [0 3 5]



In [92]:
resultados = []
for rep in range(10):
    print ('Rep:', rep)
    kf = KFold(2 ,shuffle=True, random_state=rep)
    for linhas_treino, linhas_valid in kf.split(X):
        print('Treino', linhas_treino.shape[0])
        print('Valid', linhas_valid.shape[0])
        print()
    
        X_treino, X_valid = X.iloc[linhas_treino], X.iloc[linhas_valid]
        y_treino, y_valid = y.iloc[linhas_treino], y.iloc[linhas_valid]
    
        model = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
        model.fit(X_treino, y_treino)
    
        p = model.predict(X_valid)
        acc = np.mean(y_valid == p)
        resultados.append(acc)
        print('ACC:', acc)
        print()
    
        #print(X_treino.head())
        #print()

Rep: 0
Treino 445
Valid 446

ACC: 0.7713004484304933

Treino 446
Valid 445

ACC: 0.7797752808988764

Rep: 1
Treino 445
Valid 446

ACC: 0.7443946188340808

Treino 446
Valid 445

ACC: 0.7955056179775281

Rep: 2
Treino 445
Valid 446

ACC: 0.7757847533632287

Treino 446
Valid 445

ACC: 0.7887640449438202

Rep: 3
Treino 445
Valid 446

ACC: 0.7533632286995515

Treino 446
Valid 445

ACC: 0.7573033707865169

Rep: 4
Treino 445
Valid 446

ACC: 0.7354260089686099

Treino 446
Valid 445

ACC: 0.7415730337078652

Rep: 5
Treino 445
Valid 446

ACC: 0.7219730941704036

Treino 446
Valid 445

ACC: 0.7056179775280899

Rep: 6
Treino 445
Valid 446

ACC: 0.7757847533632287

Treino 446
Valid 445

ACC: 0.7303370786516854

Rep: 7
Treino 445
Valid 446

ACC: 0.7040358744394619

Treino 446
Valid 445

ACC: 0.7348314606741573

Rep: 8
Treino 445
Valid 446

ACC: 0.7488789237668162

Treino 446
Valid 445

ACC: 0.7887640449438202

Rep: 9
Treino 445
Valid 446

ACC: 0.7623318385650224

Treino 446
Valid 445

ACC: 0.78426966

In [93]:
np.mean(resultados)

0.7550007557817302

In [22]:
variables = ['Sex_binario', 'Age']

In [23]:
def transformar_sex(valor):
    if valor == 'female':
        return 1
    else:
        return 0
train['Sex_binario'] = train['Sex'].map(transformar_sex)

In [24]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Sex_binario  
0      0         A/5 21171   7.2500   NaN        S            0  
1      0          PC 17599  71.2833   C85        C            1  
2      0  STON/O2. 3101282   7.9250   NaN        S            1  
3      0            113803  53.1000  C123        S            1  
4      0            373450   8.0500   NaN        S            0

In [25]:
variables = ['Sex_binario', 'Age']

In [26]:
X = train[variables]
y = train['Survived']

In [27]:
X.head()

Sex_binario   Age
0            0  22.0
1            1  38.0
2            1  26.0
3            1  35.0
4            0  35.0

In [28]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [56]:
model.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [74]:
X_prev = test[variables]
X_prev = X_prev.fillna(-1)

In [75]:
test['Sex_binario'] = test['Sex'].map(transformar_sex)

In [76]:
X = X.fillna(-1)

In [78]:
X_prev.head()

Sex_binario   Age
0            0  34.5
1            1  47.0
2            0  62.0
3            0  27.0
4            1  22.0

In [79]:
p = model.predict(X_prev)
p

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [80]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  Sex_binario  
0  34.5      0      0   330911   7.8292   NaN        Q            0  
1  47.0      1      0   363272   7.0000   NaN        S            1  
2  62.0      0      0   240276   9.6875   NaN        Q            0  
3  27.0      0      0   315154   8.6625   NaN        S            0  
4  22.0      1      1  3101298  12.2875   NaN        S            1

In [64]:
# CRIAR SUBMISSION

In [65]:
sub = pd.Series(p, index=test['PassengerId'],name='Survived')
sub.shape

(418,)

In [66]:
sub.to_csv("model2.csv", header=True)

In [40]:
!head -n10 first_model.csv

PassengerId,Survived
892,0
893,1
894,0
895,1
896,1
897,0
898,1
899,0
900,1
